substitutions:
  device_name: incubation-chamber-monitor
#   friendly_name: House
#   device_description: "Measure your energy consumption with the pulse LED on your smart meter"
  temp_pin: GPIO14
#   relay_pin: GPIO1
  # screen_sck_pin: GPIO9
  # screen_sda_pin: GPIO10
  # pulse_rate: '1000'
  
esphome:
  name: "${device_name}"
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: incubation-chamber
    password: !secret fallback_password

  # manual_ip:
  #   static_ip: 192.168.1.63
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0

captive_portal:

# web_server:
#   port: 80
#   auth:
#     username: !secret esphome_web_username
#     password: !secret esphome_web_password

# i2c:
#   sda: ${screen_sda_pin}
#   scl: ${screen_sck_pin}

# font:
#   - file: "fonts/Comic Sans MS.ttf"
#     id: my_font
#     size: 20

# display:
#   - platform: ssd1306_i2c
#     model: "SSD1306 128x64"
#     # reset_pin: D0
#     address: 0x3C
#     lambda: |-
#       it.print(0, 0, id(font), "Hello World!");

sensor:
  - platform: dht
    # model: DHT22_TYPE2
    pin: ${temp_pin}
    temperature:
      name: "Incubation Chamber Temp"
      id: temp
      # on_value_range:
      #   - above: 26.9
      #     then:
      #       - switch.turn_off: relay_1
      #   - below: 26.9
      #     then:
      #       - switch.turn_on: relay_1
    humidity:
      name: "Incubation Chamber Humidity"
      id: hum
    update_interval: 6s

# switch:
#   - platform: gpio
#     pin: ${relay_pin}
#     id: relay_1
#     name: relay_1
